# version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=alem
      - POSTGRES_DB=liderboard
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: go-app
    depends_on:
      - db
      - minio
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://admin:alem@db:5432/liderboard?sslmode=disable
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: >
      sh -c "
        ./wait-for-it.sh db:5432 --timeout=60 --strict -- echo 'Postgres is up';
        ./wait-for-it.sh minio:9000 --timeout=60 --strict -- echo 'MinIO is up';
        ./app
      "      

volumes:
  minio_data:
